---
title: "PRED-LD Table 5 (part 1)"
author: "Georgios A. Manios"

output: html_document
---
 

```{r echo=TRUE, message=FALSE, warning=FALSE}
# Imports
library(readxl)
library(readr)
library(dplyr)

# ADHD dataset
ADHD <- read.delim(
  "imp_real_values_harm_new_input/ADHD_chrom1_real_values_new_input.txt", 
  sep = "\t", 
  
  stringsAsFactors = FALSE 
)

# CAD dataset
CAD <- read.delim(
  "imp_real_values_harm_new_input/CAD_EUR_chr1_3925_real_values_new_input.txt", 
  sep = "\t", 
  
  stringsAsFactors = FALSE 
)

# Colorectal Cancer dataset
Colorectal_Cancer <- read.delim(
  "imp_real_values_harm_new_input/Colorectal_Cancer_4097_EAS_chrom1_real_values_new_input.txt", 
  sep = "\t", 
  
  stringsAsFactors = FALSE 
)

# Double Eyelid dataset
Double_Eyelid <- read.delim(
  "imp_real_values_harm_new_input/Double_eylid_4021_EAS_chorm1_real_values_new_input.txt", 
  sep = "\t", 
  
  stringsAsFactors = FALSE 
)

# Epilepsy dataset
Epilepsy <- read.delim(
  "imp_real_values_harm_new_input/Epilepsy_chrom1_real_values_new_input.txt", 
  sep = "\t", 
  
  stringsAsFactors = FALSE 
)

# GFR_AFR dataset
GFR_AFR <- read.delim(
  "imp_real_values_harm_new_input/GFR_AFR_4054_chrom1_real_values_new_input.txt", 
  sep = "\t", 
  
  stringsAsFactors = FALSE )

# GFR_EUR dataset
GFR_EUR <- read.delim(
  "imp_real_values_harm_new_input/GFR_EUR_4053_chrom1_real_values_new_input.txt", 
  sep = "\t", 
  
  stringsAsFactors = FALSE )

# UACR dataset
UACR <- read.delim(
  "imp_real_values_harm_new_input/UACR_chrom1_real_values_new_input.txt", 
  sep = "\t", 
  
  stringsAsFactors = FALSE )






#Read all SSIMP results
SSIMP_ADHD <-  read_delim("SSIMP/SSIMP_results/SSIMP_ADHD_EUR_chr1.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE)
SSIMP_CAD <-read_delim("SSIMP/SSIMP_results/SSIMP_CAD_EUR_chr1.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE) 
SSIMP_C_CANCER <-  read_delim("SSIMP/SSIMP_results/SSIMP_COL_CANCER_EAS_chr1.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE)
SSIMP_D_LID <- read_delim("SSIMP/SSIMP_results/SSIMP_DLID_EAS_chr1.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE)
SSIMP_EP <-  read_delim("SSIMP/SSIMP_results/SSIMP_EPILEPSY_EUR_chr1.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE)
SSIMP_GFR_AFR <-  read_delim("SSIMP/SSIMP_results/SSIMP_GFR_AFR_chr1.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE)
SSIMP_GFR_EUR <-  read_delim("SSIMP/SSIMP_results/SSIMP_GFR_EUR_chr1.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE)
SSIMP_UACR <-  read_delim("SSIMP/SSIMP_results/SSIMP_UACR_EUR_chr1.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE)

#Read all DIST results
DIST_ADHD <-read_delim("DIST/DIST_results/DIST_ADHD_EUR_chr1.txt", delim = " ", escape_double = FALSE, trim_ws = TRUE)
DIST_CAD <-read_delim("DIST/DIST_results/DIST_CAD_EUR_chr1.txt", delim = " ", escape_double = FALSE, trim_ws = TRUE)
DIST_C_CANCER <-read_delim("DIST/DIST_results/DIST_COL_CANCER_EAS_chr1.txt", delim = " ", escape_double = FALSE, trim_ws = TRUE)
DIST_D_LID <-read_delim("DIST/DIST_results/DIST_D_LID_EAS_chr1.txt", delim = " ", escape_double = FALSE, trim_ws = TRUE)
DIST_EP <-read_delim("DIST/DIST_results/DIST_EPILPESY_EUR_chr1.txt", delim = " ", escape_double = FALSE, trim_ws = TRUE)
DIST_GFR_AFR <-read_delim("DIST/DIST_results/DIST_GFR_AFR_chr1.txt", delim = " ", escape_double = FALSE, trim_ws = TRUE)
DIST_GFR_EUR <-read_delim("DIST/DIST_results/DIST_GFR_EUR_chr1.txt", delim = " ", escape_double = FALSE, trim_ws = TRUE)
DIST_UACR <-read_delim("DIST/DIST_results/DIST_UACR_chr1.txt", delim = " ", escape_double = FALSE, trim_ws = TRUE)







#FILTER SSIMP
SSIMP_ADHD <- SSIMP_ADHD[SSIMP_ADHD$source == 'SSIMP',]
SSIMP_CAD <- SSIMP_CAD[SSIMP_CAD$source == 'SSIMP',]
SSIMP_C_CANCER <- SSIMP_C_CANCER[SSIMP_C_CANCER$source == 'SSIMP',]
SSIMP_D_LID <- SSIMP_D_LID[SSIMP_D_LID$source == 'SSIMP',]
SSIMP_EP <- SSIMP_EP[SSIMP_EP$source == 'SSIMP',]
SSIMP_GFR_AFR <- SSIMP_GFR_AFR[SSIMP_GFR_AFR$source == 'SSIMP',]
SSIMP_GFR_EUR <- SSIMP_GFR_EUR[SSIMP_GFR_EUR$source == 'SSIMP',]
SSIMP_UACR <- SSIMP_UACR[SSIMP_UACR$source == 'SSIMP',]






#FILTER DIST
DIST_ADHD <- DIST_ADHD[DIST_ADHD$type == 0,]
DIST_CAD <- DIST_CAD[DIST_CAD$type == 0,]
DIST_C_CANCER <- DIST_C_CANCER[DIST_C_CANCER$type == 0,]
DIST_D_LID <- DIST_D_LID[DIST_D_LID$type == 0,]
DIST_EP <- DIST_EP[DIST_EP$type == 0,]
DIST_GFR_AFR <- DIST_GFR_AFR[DIST_GFR_AFR$type == 0,]
DIST_GFR_EUR <- DIST_GFR_EUR[DIST_GFR_EUR$type == 0,]
DIST_UACR <- DIST_UACR[DIST_UACR$type == 0,]



# Rename SSIMP datasets
colnames(SSIMP_ADHD)[colnames(SSIMP_ADHD) == "Allele1"] <- "A2"
colnames(SSIMP_ADHD)[colnames(SSIMP_ADHD) == "Allele2"] <- "A1"
colnames(SSIMP_ADHD)[colnames(SSIMP_ADHD) == "z_imp"] <- "z"
colnames(SSIMP_ADHD)[colnames(SSIMP_ADHD) == "SNP"] <- "snp"

colnames(SSIMP_CAD)[colnames(SSIMP_CAD) == "Allele1"] <- "A2"
colnames(SSIMP_CAD)[colnames(SSIMP_CAD) == "Allele2"] <- "A1"
colnames(SSIMP_CAD)[colnames(SSIMP_CAD) == "z_imp"] <- "z"
colnames(SSIMP_CAD)[colnames(SSIMP_CAD) == "SNP"] <- "snp"

colnames(SSIMP_C_CANCER)[colnames(SSIMP_C_CANCER) == "Allele1"] <- "A2"
colnames(SSIMP_C_CANCER)[colnames(SSIMP_C_CANCER) == "Allele2"] <- "A1"
colnames(SSIMP_C_CANCER)[colnames(SSIMP_C_CANCER) == "z_imp"] <- "z"
colnames(SSIMP_C_CANCER)[colnames(SSIMP_C_CANCER) == "SNP"] <- "snp"

colnames(SSIMP_D_LID)[colnames(SSIMP_D_LID) == "Allele1"] <- "A2"
colnames(SSIMP_D_LID)[colnames(SSIMP_D_LID) == "Allele2"] <- "A1"
colnames(SSIMP_D_LID)[colnames(SSIMP_D_LID) == "z_imp"] <- "z"
colnames(SSIMP_D_LID)[colnames(SSIMP_D_LID) == "SNP"] <- "snp"

colnames(SSIMP_EP)[colnames(SSIMP_EP) == "Allele1"] <- "A2"
colnames(SSIMP_EP)[colnames(SSIMP_EP) == "Allele2"] <- "A1"
colnames(SSIMP_EP)[colnames(SSIMP_EP) == "z_imp"] <- "z"
colnames(SSIMP_EP)[colnames(SSIMP_EP) == "SNP"] <- "snp"

colnames(SSIMP_GFR_AFR)[colnames(SSIMP_GFR_AFR) == "Allele1"] <- "A2"
colnames(SSIMP_GFR_AFR)[colnames(SSIMP_GFR_AFR) == "Allele2"] <- "A1"
colnames(SSIMP_GFR_AFR)[colnames(SSIMP_GFR_AFR) == "z_imp"] <- "z"
colnames(SSIMP_GFR_AFR)[colnames(SSIMP_GFR_AFR) == "SNP"] <- "snp"

colnames(SSIMP_GFR_EUR)[colnames(SSIMP_GFR_EUR) == "Allele1"] <- "A2"
colnames(SSIMP_GFR_EUR)[colnames(SSIMP_GFR_EUR) == "Allele2"] <- "A1"
colnames(SSIMP_GFR_EUR)[colnames(SSIMP_GFR_EUR) == "z_imp"] <- "z"
colnames(SSIMP_GFR_EUR)[colnames(SSIMP_GFR_EUR) == "SNP"] <- "snp"

colnames(SSIMP_UACR)[colnames(SSIMP_UACR) == "Allele1"] <- "A2"
colnames(SSIMP_UACR)[colnames(SSIMP_UACR) == "Allele2"] <- "A1"
colnames(SSIMP_UACR)[colnames(SSIMP_UACR) == "z_imp"] <- "z"
colnames(SSIMP_UACR)[colnames(SSIMP_UACR) == "SNP"] <- "snp"




# Rename DIST datasets
colnames(DIST_ADHD)[colnames(DIST_ADHD) == "a1"] <- "A2"
colnames(DIST_ADHD)[colnames(DIST_ADHD) == "a2"] <- "A1"
colnames(DIST_ADHD)[colnames(DIST_ADHD) == "rsid"] <- "snp"

colnames(DIST_CAD)[colnames(DIST_CAD) == "a1"] <- "A2"
colnames(DIST_CAD)[colnames(DIST_CAD) == "a2"] <- "A1"
colnames(DIST_CAD)[colnames(DIST_CAD) == "rsid"] <- "snp"

colnames(DIST_C_CANCER)[colnames(DIST_C_CANCER) == "a1"] <- "A2"
colnames(DIST_C_CANCER)[colnames(DIST_C_CANCER) == "a2"] <- "A1"
colnames(DIST_C_CANCER)[colnames(DIST_C_CANCER) == "rsid"] <- "snp"

colnames(DIST_D_LID)[colnames(DIST_D_LID) == "a1"] <- "A2"
colnames(DIST_D_LID)[colnames(DIST_D_LID) == "a2"] <- "A1"
colnames(DIST_D_LID)[colnames(DIST_D_LID) == "rsid"] <- "snp"

colnames(DIST_EP)[colnames(DIST_EP) == "a1"] <- "A2"
colnames(DIST_EP)[colnames(DIST_EP) == "a2"] <- "A1"
colnames(DIST_EP)[colnames(DIST_EP) == "rsid"] <- "snp"

colnames(DIST_GFR_AFR)[colnames(DIST_GFR_AFR) == "a1"] <- "A2"
colnames(DIST_GFR_AFR)[colnames(DIST_GFR_AFR) == "a2"] <- "A1"
colnames(DIST_GFR_AFR)[colnames(DIST_GFR_AFR) == "rsid"] <- "snp"

colnames(DIST_GFR_EUR)[colnames(DIST_GFR_EUR) == "a1"] <- "A2"
colnames(DIST_GFR_EUR)[colnames(DIST_GFR_EUR) == "a2"] <- "A1"
colnames(DIST_GFR_EUR)[colnames(DIST_GFR_EUR) == "rsid"] <- "snp"

colnames(DIST_UACR)[colnames(DIST_UACR) == "a1"] <- "A2"
colnames(DIST_UACR)[colnames(DIST_UACR) == "a2"] <- "A1"
colnames(DIST_UACR)[colnames(DIST_UACR) == "rsid"] <- "snp"








# Ensure filtering is applied to SSIMP datasets
SSIMP_ADHD <- SSIMP_ADHD[SSIMP_ADHD$r2.pred >= 0.5,]
SSIMP_CAD <- SSIMP_CAD[SSIMP_CAD$r2.pred >= 0.5,]
SSIMP_C_CANCER <- SSIMP_C_CANCER[SSIMP_C_CANCER$r2.pred >= 0.5,]
SSIMP_D_LID <- SSIMP_D_LID[SSIMP_D_LID$r2.pred >= 0.5,]
SSIMP_EP <- SSIMP_EP[SSIMP_EP$r2.pred >= 0.5,]
SSIMP_GFR_AFR <- SSIMP_GFR_AFR[SSIMP_GFR_AFR$r2.pred >= 0.5,]
SSIMP_GFR_EUR <- SSIMP_GFR_EUR[SSIMP_GFR_EUR$r2.pred >= 0.5,]
SSIMP_UACR <- SSIMP_UACR[SSIMP_UACR$r2.pred >= 0.5,]



# Ensure filtering is applied to DIST datasets
DIST_ADHD <- DIST_ADHD[DIST_ADHD$info >= 0.5,]
DIST_CAD <- DIST_CAD[DIST_CAD$info >= 0.5,]
DIST_C_CANCER <- DIST_C_CANCER[DIST_C_CANCER$info >= 0.5,]
DIST_D_LID <- DIST_D_LID[DIST_D_LID$info >= 0.5,]
DIST_EP <- DIST_EP[DIST_EP$info >= 0.5,]
DIST_GFR_AFR <- DIST_GFR_AFR[DIST_GFR_AFR$info >= 0.5,]
DIST_GFR_EUR <- DIST_GFR_EUR[DIST_GFR_EUR$info >= 0.5,]
DIST_UACR <- DIST_UACR[DIST_UACR$info >= 0.5,]







# Function to calculate and analyze imputation results
analyze_imputation <- function(true_file, imputed_file, trait_name, method_name, delim = "\t") {
  
  get_complement <- function(allele) {
    case_when(
      allele == "A" ~ "T",
      allele == "T" ~ "A",
      allele == "C" ~ "G",
      allele == "G" ~ "C",
      
    )
  }
  
  
  # Calculate number of imputed SNPs
  imputed_snps <- nrow(imputed_data)
  
  # Join data on "snp"
  joined_data <- inner_join(true_data, imputed_data, by = "snp", suffix = c("_true", "_imp"))
  
  # Add complement alleles to the dataset
  joined_data <- joined_data %>%
    mutate(
      REF_complement = get_complement(A2_imp),
      ALT_complement = get_complement(A1_imp)
    )
  # Modify z values
  joined_data <-joined_data %>%
    mutate(
      z_true = case_when(
        A1_imp == A1_true & A2_imp == A2_true ~ -z_true,
        A1_imp == A2_true & A2_imp == A1_true ~ z_true,
        ALT_complement == A1_true & REF_complement == A2_true~ -z_true,
        ALT_complement == A2_true & REF_complement == A1_true ~ z_true,
        TRUE ~ NA_real_
      )
    )
  
  
  
  # Calculate coverage percentage
  coverage <- (nrow(joined_data) / nrow(true_data)) * 100
  
  # Linear model for Z-scores
  z_model <- lm(joined_data$z_imp ~ joined_data$z_true)
  r2_z <- summary(z_model)$r.squared
  
  
 
  
  # Calculate -log10(p) values
  joined_data <- joined_data %>%
    mutate(
      log10p_true = -log10( 2*(pnorm(-abs(z_imp)))),
      log10p_imp = -log10( 2*(pnorm(-abs(z_true)))) 
    )
  
  # Linear model for -log10(p)
  log10p_model <- lm(joined_data$log10p_imp ~ joined_data$log10p_true)
  r2_log10p <- summary(log10p_model)$r.squared
  
 
  
  # Return results as a dataframe row
  return(data.frame(
    Trait = trait_name,
    Method = method_name,
    Imputed_SNPs = imputed_snps,
    R2_z =  r2_z,
    R2_log10p=r2_log10p,
    Masked_SNPs_Found = nrow(joined_data),
    Imputation_Percentage = coverage
  ))
}










# List of datasets, imputed files, and their corresponding traits and methods
datasets <- list(
  list("ADHD", ADHD, SSIMP_ADHD, "SSIMP"),
  list("ADHD", ADHD, DIST_ADHD, "DIST"), 
  
  list("CAD", CAD, SSIMP_CAD, "SSIMP"),
  list("CAD", CAD, DIST_CAD, "DIST"),
  
  list("Colorectal Cancer", Colorectal_Cancer, SSIMP_C_CANCER, "SSIMP"),
  list("Colorectal Cancer", Colorectal_Cancer, DIST_C_CANCER, "DIST"),
  
  
  list("Double Eyelid", Double_Eyelid, SSIMP_D_LID, "SSIMP"),
  list("Double Eyelid", Double_Eyelid, DIST_D_LID, "DIST"),
  
  
  list("Epilepsy", Epilepsy, SSIMP_EP, "SSIMP"),
  list("Epilepsy", Epilepsy, DIST_EP, "DIST"),
  
  
  list("GFR_AFR", GFR_AFR, SSIMP_GFR_AFR, "SSIMP"),
  list("GFR_AFR", GFR_AFR, DIST_GFR_AFR, "DIST"),
  
  
  list("GFR_EUR", GFR_EUR, SSIMP_GFR_EUR, "SSIMP"),
  list("GFR_EUR", GFR_EUR, DIST_GFR_EUR, "DIST"),
  
  
  list("UACR", UACR, SSIMP_UACR, "SSIMP"),
  list("UACR", UACR, DIST_UACR, "DIST")
  
)


# Initialize an empty dataframe to store the results
results_df <- data.frame()

# Loop through datasets and run the analyze_imputation function
for (dataset in datasets) {
  trait <- dataset[[1]]
  true_data <- dataset[[2]]
  imputed_data <- dataset[[3]]
  method <- dataset[[4]]
  
  # Analyze the imputation
  result <- analyze_imputation(true_data, imputed_data, trait, method)
  
  # Convert the result to a dataframe and append it to results_df
  results_df <- rbind(results_df, as.data.frame(result))
  
}



 
DIST<- results_df[results_df$Method=='DIST',]


desired_order <- c("ADHD", "UACR", "GFR_EUR", "GFR_AFR", "Epilepsy", 
                   "Colorectal Cancer", "Double Eyelid", "CAD")

# Reorder the dataframe
DIST <- DIST %>%
  mutate(Trait = factor(Trait, levels = desired_order)) %>%
  arrange(Trait)
```

## DIST R2>0.5 
```{r echo=TRUE, message=FALSE, warning=FALSE}
## DIST R2>0.5 
print(DIST)

mean(DIST$Imputed_SNPs)

mean(DIST$R2_z)

mean(DIST$R2_log10p)

mean(DIST$Imputation_Percentage)

 

  
```
 
 
 
## SSIMP R2>0.5 
```{r echo=TRUE, message=FALSE, warning=FALSE}
 SSIMP <- results_df[results_df$Method=='SSIMP',]


desired_order <- c("ADHD", "UACR", "GFR_EUR", "GFR_AFR", "Epilepsy", 
                   "Colorectal Cancer", "Double Eyelid", "CAD")

# Reorder the dataframe
SSIMP <- SSIMP %>%
  mutate(Trait = factor(Trait, levels = desired_order)) %>%
  arrange(Trait)


print(SSIMP)

mean(SSIMP$Imputed_SNPs)

mean(SSIMP$R2_z)

mean(SSIMP$R2_log10p)

mean(SSIMP$Imputation_Percentage)

```
 